spring.application.name=Pharmacy
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/PharmacyDB
spring.datasource.username=root
spring.datasource.password=100825
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=123456
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.packages-to-scan=Pharmacy.Controllers
spring.jackson.default-property-inclusion=non_null
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false

#JWT config
app.jwt.secret=pharmacySecretKey2026WithAtLeast32CharactersLong
app.jwt.expiration.access=3600000
app.jwt.expiration.refresh=604800000

