spring.application.name=Pharmacy
server.port=${PORT:8080}
java.runtime.version=17

#MySQL
spring.datasource.url=${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.packages-to-scan=Pharmacy.Controllers
spring.jackson.default-property-inclusion=non_null
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.favor-path-extension=false

#JWT config
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration.access=3600000

# VNPay sandbox
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmn-code=YOUR_TMN_CODE
vnpay.hash-secret=YOUR_HASH_SECRET
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return

# Connection pool — tăng lên cho production
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
